# .scrutinizer.yml
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage: true
checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'example/*'